name: Trigger Portfolio Sync

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/content/blog/**'

jobs:
  notify-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portfolio Blog Sync
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Mogeshaue/portfolio-blog
          event-type: blog-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
